import '../models/course.dart';
import '../models/schedule.dart';

final debugLongContentSchedule = Schedule(
  semesterLabel: 'Debug 超长内容测试学期',
  generatedAt: DateTime(2026, 5, 7, 12),
  isStale: false,
  lastSyncedAt: DateTime(2026, 5, 7, 12),
  courses: const [
    Course(
      name: '超长课程名称测试：面向对呃呃呃呃呃呃呃呃呃呃呃呃呃呃呃呃呃呃呃呃呃呃呃呃呃呃呃呃呃呃呃呃呃呃呃呃呃呃象程序设计与大型软件工程实践综合训练',
      code: 'SIT',
      teacher: 'Sam',
      room: 'S4408计算机专业实验室',
      weekday: 1,
      lessonStart: 1,
      lessonEnd: 2,
      rawWeeks: '1-18(周)',
      parsedWeeks: [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
      ],
    ),
    Course(
      name: '超长课程名称测试：JavaWeb程序设计SIT企业级应用开发与部署',
      code: 'JavaWeb程序设计SIT',
      teacher: 'Alexander',
      room: 'BY305',
      weekday: 2,
      lessonStart: 1,
      lessonEnd: 2,
      rawWeeks: '1-18(周)',
      parsedWeeks: [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
      ],
    ),
    Course(
      name: '超长课程名称测试：人工智能导论机器学习深度学习实验课程',
      code: 'AI-LAB / ML-DEEP',
      teacher: '王老师',
      room: 'S4408计算机专业实验室 / BY409智慧教室',
      weekday: 3,
      lessonStart: 3,
      lessonEnd: 4,
      rawWeeks: '1-18(周)',
      parsedWeeks: [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
      ],
    ),
    Course(
      name: '超长课程名称测试：移动应用开发Flutter跨平台项目实训',
      code: 'FLUTTER-PROJECT-SIT',
      teacher: '李四',
      room: '东区实验楼A305',
      weekday: 4,
      lessonStart: 5,
      lessonEnd: 6,
      rawWeeks: '1-18(周)',
      parsedWeeks: [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
      ],
    ),
    Course(
      name: '超长课程名称测试：数据库系统原理与分布式事务一致性实验',
      code: 'DB-SYSTEM / TX',
      teacher: '赵六',
      room: '图书馆报告厅 / S3301',
      weekday: 5,
      lessonStart: 7,
      lessonEnd: 8,
      rawWeeks: '1-18(周)',
      parsedWeeks: [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
      ],
    ),
    Course(
      name: '超长课程名称测试：软件测试技术自动化测试性能测试安全测试综合实践',
      code: 'TEST-AUTO-PERF-SEC',
      teacher: 'Debug Teacher',
      room: 'BY999超长地点名称测试教室',
      weekday: 1,
      lessonStart: 9,
      lessonEnd: 10,
      rawWeeks: '1-18(周)',
      parsedWeeks: [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
      ],
    ),
    Course(
      name: '超长课程名称测试：编译原理语法分析语义分析代码生成课程设计',
      code: 'COMPILER / COURSE-DESIGN',
      teacher: 'Debug',
      room: 'S1201 / S1202 / S1203',
      weekday: 6,
      lessonStart: 9,
      lessonEnd: 10,
      rawWeeks: '1-18(周)',
      parsedWeeks: [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
      ],
    ),
  ],
);
